import { getEnvCsv, getEnvInt, getEnvString } from './env'

export const CHECKOUT_COUNTRY_SUGGESTIONS_LIMIT = 18
export const CHECKOUT_COUNTRY_FALLBACK = 'Otros'
export const CHECKOUT_WHATSAPP_NUMERO = getEnvString('VITE_WHATSAPP_NUMERO', '').replace(/\D/g, '')
export const CHECKOUT_WHATSAPP_BASE_URL = getEnvString('VITE_WHATSAPP_BASE_URL', '')
export const CHECKOUT_ENV = getEnvString('VITE_CHECKOUT_ENV', 'production')
export const CHECKOUT_WEB_COMPONENTS_URL = getEnvString('VITE_CHECKOUT_WEB_COMPONENTS_URL', '')
export const CHECKOUT_PERSONA_SDK_URL = getEnvString('VITE_PERSONA_SDK_URL', '')
export const CHECKOUT_LOCALE = getEnvString('VITE_CHECKOUT_LOCALE', 'en-US')
export const CHECKOUT_POLLING_MS = getEnvInt('VITE_CHECKOUT_POLLING_MS', 4_000, {
  min: 1_000,
  max: 30_000,
})
export const CHECKOUT_CARD_SCHEMES = getEnvCsv('VITE_CHECKOUT_CARD_SCHEMES', [
  'mastercard',
  'american_express',
])

export const CHECKOUT_COUNTRIES = [
  'Albania',
  'Alemania',
  'Andorra',
  'Antigua y Barbuda',
  'Argentina',
  'Armenia',
  'Austria',
  'Azerbaiyan',
  'Bahamas',
  'Barbados',
  'Belgica',
  'Belice',
  'Bielorrusia',
  'Bolivia',
  'Bosnia y Herzegovina',
  'Brasil',
  'Bulgaria',
  'Canada',
  'Chile',
  'Chipre',
  'Colombia',
  'Costa Rica',
  'Croacia',
  'Cuba',
  'Dinamarca',
  'Dominica',
  'Ecuador',
  'El Salvador',
  'Eslovaquia',
  'Eslovenia',
  'Espana',
  'Estados Unidos',
  'Estonia',
  'Finlandia',
  'Francia',
  'Georgia',
  'Granada',
  'Grecia',
  'Guatemala',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungria',
  'Irlanda',
  'Islandia',
  'Italia',
  'Jamaica',
  'Kazajistan',
  'Kosovo',
  'Letonia',
  'Liechtenstein',
  'Lituania',
  'Luxemburgo',
  'Malta',
  'Mexico',
  'Moldavia',
  'Monaco',
  'Montenegro',
  'Nicaragua',
  'Noruega',
  'Paises Bajos',
  'Panama',
  'Paraguay',
  'Peru',
  'Polonia',
  'Portugal',
  'Reino Unido',
  'Republica Checa',
  'Republica Dominicana',
  'Rumania',
  'Rusia',
  'San Cristobal y Nieves',
  'San Marino',
  'San Vicente y las Granadinas',
  'Santa Lucia',
  'Serbia',
  'Suecia',
  'Suiza',
  'Surinam',
  'Trinidad y Tobago',
  'Ucrania',
  'Uruguay',
  'Vaticano',
  'Venezuela',
  CHECKOUT_COUNTRY_FALLBACK,
]