PEDIDO_ESTADO_PENDIENTE = "pendiente"
PEDIDO_ESTADO_PAGADO = "pagado"
PEDIDO_ESTADO_CANCELADO = "cancelado"
PEDIDO_ESTADO_FALLIDO = "fallido"

PEDIDO_ESTADOS_VALIDOS = {
	PEDIDO_ESTADO_PENDIENTE,
	PEDIDO_ESTADO_PAGADO,
	PEDIDO_ESTADO_CANCELADO,
	PEDIDO_ESTADO_FALLIDO,
}


ROL_ADMIN = "admin"
ROL_USUARIO = "usuario"


CACHE_KEY_PRODUCTOS_LIST = "productos:list"
CACHE_KEY_PRODUCTOS_LIST_PREFIX = "productos:list:"
CACHE_KEY_CATEGORIAS_LIST_PREFIX = "categorias:list:"
CACHE_KEY_USUARIOS_LIST_PREFIX = "usuarios:list:"
CACHE_KEY_USUARIO_TICKETS_PREFIX = "usuario:tickets:"
CACHE_KEY_PEDIDOS_USUARIO_PREFIX = "usuario:pedidos:"
CACHE_KEY_PEDIDOS_METRICAS_PREFIX = "pedidos:metricas:"
CACHE_KEY_PAYMENT_SESSION_PREFIX = "payments:session:"

CACHE_TTL_PRODUCTOS_SEGUNDOS = 300
CACHE_TTL_TICKETS_USUARIO_SEGUNDOS = 120
CACHE_TTL_USUARIOS_SEGUNDOS = 120
CACHE_TTL_CATEGORIAS_SEGUNDOS = 180
CACHE_TTL_PEDIDOS_USUARIO_SEGUNDOS = 120

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
